### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by lukasbystricky** [bob-reus/edgar-saltus_mr-incouls-misadventure#1]
- [x] Run semanicate, it makes one change I think should be accepted (I'm running the latest toolkit, so if nothing happens for you that's fine)
- [x] Add The Online Distributed Proofreading team to content.opf
- [x] Some unsemanticated `<i>`s hanging around, I think those should be switched to `<em>` or unitalicized 
- [x] Remove italics from "père", "entr'acte", "régisseur", "amour propre"
- [x] "chapeau" is also in MW, but maybe you want to keep the italics in context, I'll leave that up to you
- [x] Editorial change "private docent" to "[privatdozent]( https://www.merriam-webster.com/dictionary/privatdozent)" and remove italics

**Comment by bob-reus** [comment]
Thank you for the review! All corrections have been pushed. A couple of notes:

* "chapeau" is kept italicized in this context
* Nuance in "_nuance_ Rachel" is also still italicized, with added `xml:lang="fr"` attribute.  I'm not 100% certain, but I think "nuance" is meant to be read as a French word here, in its meaning of 'shade / gradation of color.' Not much else makes sense in this context.

**Comment by lukasbystricky** [comment]
Ok, looks good. One final thing: does S. T. in chapter 5 stand for "schrecklich teuer"? If it does then the personal-name semantic should be removed and it should be made an initialism, see [here](https://standardebooks.org/manual/1.7.4/single-page#8.10.2).

**Comment by bob-reus** [comment]
You're right, thanks for spotting that. I just pushed the change.

**Comment by lukasbystricky** [comment]
Ok, maybe that makes sense as an unsemanticated abbreviation. Looks good to me, I'll pass it off to Alex.

**Comment by bob-reus** [comment]
Oops, that wasn't intentional. It was late here at the time, and in my rush to complete the book I misread your comment. I'm glad it was acceptable.
